# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -o "samora" ./main.go

      - name: Upload samora-lang artifact
        uses: actions/upload-artifact@v3
        with:
          name: samora-lang
          path: samora

      - name: Create Unix release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        uses: actions/create-release@v1
        with:
          tag_name: v1.0 # Defina a tag da versão
          release_name: Unix Release v1.0 # Nome da versão
          draft: false
          prerelease: false

      - name: Attach Binaries to Release
        id: attach_binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: samora
          asset_name: samora-lang
          asset_content_type: application/octet-stream

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       samora
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build deb
        run: |
          mkdir -p .debpkg/usr/bin
          cp samora .debpkg/usr/bin/samora
          chmod +x .debpkg/usr/bin/samora

          mkdir -p .debpkg/DEBIAN

      - uses: jiro4989/build-deb-action@v3
        with:
          package: samora-lang
          package_root: .debpkg
          maintainer: Samora-Lang Community
          version: 1.0.0 # ${{ github.ref }} # refs/tags/v*.*.*
          arch: "amd64"
          # depends: 'libc6 (>= 2.2.1), git'
          desc: "A Simple Interpreted Programming Language just for Educational Purposes."

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: |
          go build -o "samora.exe" ./main.go

      - name: Upload samora-lang artifact
        uses: actions/upload-artifact@v3
        with:
          name: samora-lang-win
          path: samora.exe
